nameOverride: ""
fullnameOverride: ""
replicaCount: 1
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

containerPort: 5000

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

env: {}
secretEnv: {}

resources: {}

readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 2
  failureThreshold: 3

serviceAccount:
  create: true
  name: ""
